DROP INDEX IF EXISTS source_wiki_attempts_batch;
DROP INDEX IF EXISTS source_wiki_one_running_target;
ALTER TABLE source_wiki_attempts DROP COLUMN IF EXISTS batch_id;
ALTER TABLE source_wiki_attempts DROP COLUMN IF EXISTS topic_kind;
ALTER TABLE source_wiki_attempts DROP COLUMN IF EXISTS topic_key;
ALTER TABLE source_wiki_attempts DROP COLUMN IF EXISTS staged_at;
ALTER TABLE source_wiki_attempts DROP COLUMN IF EXISTS staged_page_version;
ALTER TABLE source_wiki_attempts DROP COLUMN IF EXISTS result_kind;
CREATE UNIQUE INDEX IF NOT EXISTS source_wiki_one_running_module
    ON source_wiki_attempts(tenant_id, knowledge_base_id, source_id, module_path) WHERE status='running';
DROP TABLE IF EXISTS source_wiki_batch_calls;
DROP TABLE IF EXISTS source_wiki_topics;
DROP INDEX IF EXISTS source_wiki_one_running_batch;
ALTER TABLE source_wiki_batches DROP COLUMN IF EXISTS publish_cursor;
ALTER TABLE source_wiki_batches DROP COLUMN IF EXISTS qa_deadline_at;
ALTER TABLE source_wiki_batches DROP COLUMN IF EXISTS qa_approved_at;
ALTER TABLE source_wiki_batches DROP COLUMN IF EXISTS qa_approval_digest;
ALTER TABLE source_wiki_batches DROP COLUMN IF EXISTS revalidation_attempt_id;
DROP INDEX IF EXISTS source_wiki_batches_status_deadline;
DROP INDEX IF EXISTS source_wiki_batches_source_created;
DROP TABLE IF EXISTS source_wiki_batches;
